#!/usr/bin/env bash

# Intall terminal
brew install ghostty

# Install jq
brew install jq

# Install Tmux and fzf
brew install tmux fzf

# Install neovim, ripgrep
brew install neovim
brew install ripgrep
