#!/usr/bin/env bash
# Requires JQ and the AWS CLI

if [[ -z "${1}" || -z "${2}" ]]; then
  echo "Usage: aws-login AWS_PROFILE MFA_CODE"
  return
fi

if ! command -v jq &> /dev/null; then
  echo "Error: This script requires that you install 'jq'"
  return
fi

ROLE_ARN=$(aws configure get "profile.${1}.role_arn")
SERIAL_ARN=$(aws configure get profile.${1}.mfa_serial)
SESSION_NAME="${SERIAL_ARN##*/}"

# Validate these variables actually have values
if [[ -z "${ROLE_ARN}" || -z "${SERIAL_ARN}" ]];then
  echo "Error: Please choose a valid profile. It must contain 'role_arn' and 'mfa_serial'"
  return
fi

# Unset existing values as this will cause the assume role to fail
unset AWS_ACCESS_KEY_ID
unset AWS_CREDENTIAL_EXPIRATION
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_PROFILE

JSON=$(aws sts assume-role --role-arn ${ROLE_ARN} --role-session-name ${SESSION_NAME} --serial-number ${SERIAL_ARN} --token-code ${2})

if [ $? -eq 0 ]; then
  export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' <<< "${JSON}")
  export AWS_CREDENTIAL_EXPIRATION=$(jq -r '.Credentials.Expiration' <<< "${JSON}")
  export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' <<< "${JSON}")
  export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' <<< "${JSON}")
  export AWS_PROFILE="${1}"
else
  echo "Error: Unable to get temporary credentials for role ${ROLE_ARN}"
fi

