#!/usr/bin/env bash

# Install it in opt for the linux version
if [[ "$OSTYPE" == linux-* ]]; then
  BASE="/opt/nvim-linux-x86_64"
  BIN="${BASE}/bin"

  curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
  echo "This script requires sudo to remove old versions from $BASE and save the new one there."
  sudo rm -rf /opt/nvim-linux-x86_64
  sudo tar -C /opt -xvf nvim-linux-x86_64.tar.gz
  rm nvim-linux-x86_64.tar.gz

  # If the user does not have neovim in the path, remind them to set it
  if ! [[ $PATH =~ $BIN ]]; then
    echo "Please add ${BIN} to your PATH"
  fi

  echo "Neovim successfully installed/updated"

else
  echo "This script is currently only supported in linux environments"
fi

